### ISSUE TITLE
Distorsioned badges 

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community-edu#10]
On Desktop:
1. Use Responsive Design View and set it between 992x1280 and 1197x1280

Actual result:
- the badges get distorsioned on resolutions between 992x1280 and 1197x1280

Expected result:
-  the badges should zoom in zoom out proportionally so their look stays the same or if not zoomable should never change size. 

See pic:

![photo_2015-04-01_15-18-30](https://cloud.githubusercontent.com/assets/1391451/6940784/b2f2cf44-d882-11e4-8b48-2334a75a30ea.jpg)

**Comment by debloper** [comment]
Failed to reproduce. Fixed by #11 maybe?

**Comment by ioana-chiorean** [comment]
Verified!
