### ISSUE TITLE
Make Drop Down Menu + Responsiveness Work

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/community-edu#18]
Twitter Bootstrap, the nav menu  collapses with media queries.
Clicking on the nav icon, expands the menu, but not the subnav - and thus there is never a subnav in mobile.

I tried a LOT Of things to get around this, in part it might be because the top menu items are also links (vrs just clicks)  .  Similar topic here:  http://stackoverflow.com/questions/11926028/bootstrap-dropdown-in-collapse   but we are looking at bootstrap 3

For now I have set responsive to 1px to avoid this problem, but of course all that means now is you can see the menu in mobile, but there's no mobile view :S 

need to figure out how to make sub menu display for responsive mode.

You can see the media variables I changed here:   https://github.com/emmairwin/mozilla-community-edu/commit/dbfa6f9b863bc5b4c132907006b53808992279e3

**Comment by asdofindia** [comment]
Is it okay to work on this?

**Comment by emmairwin** [comment]
@asdofindia oh my goodness yes.
But have since removed the submenu so this doens't break.
Can you email me directly and I can give you instructions on how to recreate?  Have you played with Jekyll locally before?
