### ISSUE TITLE
Website display si broken in smaller resolutions

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community-edu#19]
On Desktop:
1. Tools ->Developer -> Open Responsive Design View 
2. Try to website in resolution lower than 970xAnything

ActualResult:
- the look is broken, the header is not zoomable 

![screen shot 2015-04-03 at 15 41 25](https://cloud.githubusercontent.com/assets/1391451/6982264/0faabbde-da18-11e4-82f8-862d9e8cb5da.png)

**Comment by emmairwin** [comment]
dependent on :  https://github.com/emmairwin/mozilla-community-edu/issues/18

I had to kill the responsiveness to make the submenu show in mobile view.  It's a hack :(  but had to, for those needing the submenu.

**Comment by emmairwin** [comment]
@ioana-chiorean can you test again?
I decided to restore responiveness and just remove the submenu until we can get that working.  Thanks!

**Comment by emmairwin** [comment]
think this looks better now, please re-open if you find more problems.
