### ISSUE TITLE
Calendar for callpoints to one protected by Moz Credentials

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community-edu#20]
On first page go to:
Join our Community Education Call! <3

which links to :

https://www.google.com/calendar/hosted/mozilla.com/event?action=TEMPLATE&tmeid=aHZoc2M2OXU4dnVtcGVodmVnMWdlajNqbjhfMjAxNTAyMDVUMTcwMDAwWiBlaXJ3aW5AbW96aWxsYS5jb20&tmsrc=eirwin%40mozilla.com

![screenshot 2015-04-04 09 24 28](https://cloud.githubusercontent.com/assets/1391451/6991693/84881b06-daac-11e4-96e0-8e6b5ff6b480.png)

**Comment by ioana-chiorean** [comment]
Is this the correct link @emmairwin : http://www.timeanddate.com/worldclock/fixedtime.html?msg=Community+Education+Call&iso=20150312T10&p1=256&ah=1 ?

**Comment by ioana-chiorean** [comment]
Or this: https://www.google.com/calendar/event?action=TEMPLATE&hl=en&text=Community%20Education%20Call&dates=20150423T100000%2F20150423T110000&location&ctz=America%2FVancouver&details=Agenda%3A%20%20https%3A%2F%2Fremo.etherpad.mozilla.org%2Fcommunity-education-march-12-2015%0AWiki%3A%20%20https%3A%2F%2Fwiki.mozilla.org%2FCommunity_Education_Working_Group

**Comment by emmairwin** [comment]
@ioana-chiorean another great detailed catch!  I updated this to point to the wiki .
