### ISSUE TITLE
Improve Reps ( and Technical)  page

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community-edu#21]
Go to:
- http://education.mozilla-community.org/modules/reps/introduction/
- http://education.mozilla-community.org/modules/technical/introduction/

As for a better UX I think the page can have some square tiles for the available courses so the page doesn't look so empty. Also some users might miss the two options present int he header when u tap the reps/technical options. 

![screenshot 2015-04-05 17 50 39](https://cloud.githubusercontent.com/assets/1391451/7002472/e57cf032-dc53-11e4-9dfb-d8eb33edfb83.png)
![screenshot 2015-04-05 17 50 27](https://cloud.githubusercontent.com/assets/1391451/7002473/e57d1062-dc53-11e4-9d8c-f26c2dc672ad.png)

**Comment by emmairwin** [comment]
@ioana-chiorean what do you think of updates made for fix to issue #27 ?  Maybe helped here too?

**Comment by jigs1212** [comment]
Is this repo still being maintained ?

**Comment by ioana-chiorean** [comment]
@emmairwin ^

**Comment by ioana-chiorean** [comment]
@emmairwin ^

**Comment by emmairwin** [comment]
sorry for delay   https://github.com/emmairwin/mozilla-community-edu/issues/41

@jigs1212 @ioana-chiorean

**Comment by ioana-chiorean** [comment]
This is not under development anymore. 😢 
Will reopen if this will restart! 🍀 ✌🏽
