### ISSUE TITLE
Impement badges on portal

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community-edu#22]
Currently they are pointing to @emmairwin 's twitter. 

![screenshot 2015-04-07 22 23 16](https://cloud.githubusercontent.com/assets/1391451/7031768/bc7ae544-dd76-11e4-8bd4-96f89368020e.png)

**Comment by emmairwin** [comment]
Another good catch, this is a forked copy of a platform where these images were orginally 'people' and those linked to their twitter accounts. 
I had a placeholder to my twitter there, but changed it to badges which of course makes no sense now.  Removed link entirely!   Although once I've setup badges for issuing, I will update these to proper link.

Leaving open until that happens!
