### ISSUE TITLE
Calendar section has a spinning wheel but down's display anything

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community-edu#23]
When the page is loading the wheel is displayed, spins but no event or message is displayed.

![screenshot from 2015-04-08 12 56 09](https://cloud.githubusercontent.com/assets/1391451/7043271/0deaeb84-ddf1-11e4-9870-42fa04ff6bed.png)

![screenshot from 2015-04-08 13 10 06](https://cloud.githubusercontent.com/assets/1391451/7043270/0dbd057a-ddf1-11e4-9161-8e4220052b05.png)

**Comment by emmairwin** [comment]
@ioana-chiorean thanks for filing this - even though I knew that was there, it skipped my mind that it had no purpose without current calendar results :S  Thank so much, removed for now
