### ISSUE TITLE
Licensing Conflict

### ISSUE THREAD

**Issue by ghost** [emmairwin/community-edu#33]
The site says "Unless otherwise noted, all the materials on this site are licensed under a Creative Commons Attribution Share Alike 4.0 Unported license."

But there are materials like this https://www.flickr.com/photos/soulnotes/16034053449/ which are copyright (not even open for use) and others that are by-sa 2.0 and nothing is noted to say otherwise. 

So the site license conflicts with the materials which are licensed more restrictive.  I would suggest removal of the copyright material because even if there is permission to use it... It conflicts with the repo license and is incompatible.

As for the by-sa 2.0 content I would suggest appropriate attribution https://wiki.creativecommons.org/wiki/Best_practices_for_attribution

**Comment by elioqoshi** [comment]
Can confirm what Benjamin says. We should try to be especially careful with things like this if its on behalf on Mozilla. Let me know if there is any help needed for alternatives of the images used.

**Comment by emmairwin** [comment]
Great sleuthing as always Benjamin.  On review, this has to do with the site I used with pulls in creative commons licensing from a number of places.  I actually do check licenses very closely - but good lesson to go to source and not 3rd party I will review each today.

On another note, images are not in the repo, perhaps you can explain that comment a bit more.

Thanks for confirmation @elioqoshi great qa work, hard to cover everythign perfectly without more eyes. and yes I could use help finding alternates  - and better crafting the attribute license I have at the bottom of this page: http://education.mozilla-community.org/modules/about/personas/

**Comment by emmairwin** [comment]
So I replaced a couple although @elioqoshi you might have better , was important to me to represent diversity as much as possible.  pages each have the cc license, and I updated the main page to 2.0 vrs 4.0 that was left over from the fork of course in the box.  thoughts on current status>

**Comment by elioqoshi** [comment]
Great! What kind of photos do you usually need?
For any cc inquiries ping me if unsure :)

**Comment by emmairwin** [comment]
I don't usually work with photos, and I found the process really
challanging to find high quality but diverse (meaning not 'stock looking')
photos.  Basically in your day if you ever see any photos that could
improve on any I have, those suggestions would be welcome.  Thanks Elio!

On Fri, Jul 17, 2015 at 12:38 AM, Elio Qoshi notifications@github.com
wrote:

> Great! What kind of photos do you usually need?
> For any cc inquiries ping me if unsure :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emmairwin/mozilla-community-edu/issues/33#issuecomment-122204829
> .

## 

Emma Irwin
@sunnydeveloper
Mozilla Reps Mentor
