### ISSUE TITLE
Personas: Ned - "poor work"

### ISSUE THREAD

**Issue by MichaelKohler** [emmairwin/community-edu#35]
Is there a way we could change "poor work" into something more descriptive? This sounds quite irritating and demotivating for me. What do you think?

**Comment by ioana-chiorean** [comment]
Also here, as Ned is Newbie - i do not feel newbies work is poor ( I did ramp up around 10 people in my current project)   - most of times my feeling was that the work was partially done ( as they did not know all the procedures from the beginning)
Unfortunately I do not have any proposal here - shy results/work? partially done work?  but none feels like right.

**Comment by emmairwin** [comment]
So - what I was really trying to get at was that someone who turns up and does a first, second or third thing might not 

a) have all the information he/she needs to make a quality contribution
b) yet have the skills to make a quality contribution
c) understand how to navigate the system which includes the fact that we have a lot of useless bugs, or outdated bugs just lying around. 

BUT  under Diversity & Dimension list I did include skillset and skill-level, as a 'lens' so I think we can safely remove that from the Pesona description anyway.   Thanks for this great feedback
