### ISSUE TITLE
Hover on Marketpulse and Technical not working on mobile

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community-edu#8]
See Video: https://www.youtube.com/watch?v=93Zd9jFdFzM

Go to menu button, tap as hover over marketpulse to choose Firefox OS or  Technical o choose Git and Github

Pull Request for testing: https://github.com/emmairwin/mozilla-community-edu/commit/528eb65cc387530b7c4bfd91196ffc56a0f99b38 

Reported 1st by @williamq

**Comment by emmairwin** [comment]
this should work now, and if not then we can address when we do a retheme
